version: '3.8'
services:
  pg: 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: d42EF-CeDe-fg*63-bFF16*16*FCG-a*
      POSTGRES_USER: postgres
      POSTGRES_DB: railway
    ports:
      - 5432:5432